### ISSUE TITLE
RuntimeException while parsing file, if not using freight_diesel

### ISSUE THREAD

**Issue by jolo2000** [geofabrik/OpenRailRouting#19]
Hi, if I start the server with -Dgraphhopper.profiles=freight_diesel, everything works as expected.

But if I want to use a different profile, e.g.  any of freight_electric_15kvac_25kvac, freight_diesel,tgv_15kvac25kvac1.5kvdc,tgv_25kvac1.5kvdc3kvdc, then the server reports a runtime exception, while parsing the osm file.

Before starting the server, I deleted already old caches in the graph-cache directory. The OSM file germany-latest.osm.pbf is unmodified, as downloaded from geofabrik.

So, how can I get the other profiles (e.g. freight_electric_15kvac_25kvac) to work?

BR Johannes

! at io.dropwizard.Application.run(Application.java:93)
! at de.geofabrik.railway_routing.http.RailwayRoutingApplication.main(RailwayRoutingApplication.java:34)
java.lang.RuntimeException: Problem while parsing file
	at com.graphhopper.reader.osm.OSMReader.preProcess(OSMReader.java:207)
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:148)
	at de.geofabrik.railway_routing.RailwayHopper.importData(RailwayHopper.java:102)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:646)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:624)
	at de.geofabrik.railway_routing.http.RailwayRoutingManaged.start(RailwayRoutingManaged.java:34)
	at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at de.geofabrik.railway_routing.http.RailwayRoutingApplication.main(RailwayRoutingApplication.java:34)
Caused by: java.lang.NullPointerException
	at de.geofabrik.railway_routing.RailFlagEncoder.hasCompatibleElectricity(RailFlagEncoder.java:150)
	at de.geofabrik.railway_routing.RailFlagEncoder.getAccess(RailFlagEncoder.java:167)
	at com.graphhopper.routing.util.EncodingManager.acceptWay(EncodingManager.java:446)
	at com.graphhopper.reader.osm.OSMReader.filterWay(OSMReader.java:251)
	at com.graphhopper.reader.osm.OSMReader.preProcess(OSMReader.java:175)
	... 19 more

**Comment by Nakaner** [comment]
This issue is outdated because the configuration of OpenRailRouting has changed completely.
